### ISSUE TITLE
Share path is incorrectly formatted

### ISSUE THREAD

**Issue by typeiionair** [google/samba-documents-provider#16]
Provide users with some context as to how the app is expecting the share to be formatted in the text field. E.g. set placeholder to smb://10.2.1.31/path

**Comment by abclution** [comment]
Placeholder definitely would help, but I still consider mounting broken. 
Share path doesn't support nested shares. For example

smb://server/homes/username 

throws the same error, even though its a valid sharename via SMB

**Comment by ttanxu** [comment]
@abclution How is such share configured?

It wonder whether it's reported by libsmbclient as file share.

**Comment by abclution** [comment]
@ttanxu ttanxu
I guess its not a nested share, its actually folders within the main share. 
Its standard though to be able to mount SMB share subfolders as the root of the mapping.

Every other client including windows allows mount SMB share subfolders as the root of the mapping. 
The parser for the error "Share path is incorrectly formatted" is actually whats getting in the way. 
Its too strict and doesn't allow a common feature just cause its error checking.

I'm sure if it actually tried to do the mapping aka disable the path parser, it would work. 

example.

server \\nas
share \\nas\home
subfolder on share \\nas\home\tom
subfolder on share \\nas\home\dick
subfolder on share \\nas\home\harry

I should be able to map subfolders, samba supports it AFAIK

**Comment by Maxxee** [comment]
I know for sure because I got it working.
The path has to be like \\server\share[\] or smb://server/share[/]
\\server[\] or smb://server[/] does NOT work
You HAVE TO specify a share!
Note that the trailing backslash is optional.

**Comment by Maxxee** [comment]
Be aware that this piece of crap stores all passwords in plain text!
