### ISSUE TITLE
Chromebook

### ISSUE THREAD

**Issue by jmau2002** [google/samba-documents-provider#35]
Tested on Chromebook, Android 7.1.1
Mount doesnt't work, error message: Share path is incorrectly formatted. 
My format is: \\nasname\share

**Comment by ttanxu** [comment]
Try `\\nasname\share` or `smb://nasname/share`.

**Comment by ttanxu** [comment]
Besides, please consider using  [Network Share for Chromebooks](https://chrome.google.com/webstore/detail/network-file-share-for-ch/ndjpildffkeodjdaeebdhnncfhopkajk?utm_source=chrome-ntp-icon). It has better support than this one.
