### ISSUE TITLE
Any alternative for accessing mount shares?

### ISSUE THREAD

**Issue by bigretromike** [google/samba-documents-provider#36]
For those that have carrier branding on software and file_manager isin't able to access shares, is there any alternative file manager that is able to access it ?

I see that share is mounted via gmail application, but cannot find it anywhere else also 'download' don't see it.

Thank you Lenovo.

**Comment by ttanxu** [comment]
I don't think any 3rd party application can provide this access. It needs a special permission to work, and that permission can only be granted to an app signed by the same key as the one to sign the framework. Given different OEM/ODM use different keys to sign their framework, there can't be a single key that can meet this requirement. Let alone those keys can't be publicly accessible.

In Android Oreo the situation should be a bit better. There is a new test that OEM/ODM must pass, one of which effects is to guarantee such file manager exists in the framework.

**Comment by bigretromike** [comment]
To bad Oreo need to by pushed by manufatures and the mobile carrier. Older (not flagship) models wont get it. To bad because I liked the idea that google could provide more useful appliaction to it own platform, to bad carriers and phone manufactures make android fragmented. 
But still Thanks for answer, I will have to root phone to get same functionality then.

Have a good day.
