### ISSUE TITLE
Android TV share access

### ISSUE THREAD

**Issue by mpiet1** [google/samba-documents-provider#39]
Hello,
I have a Sony ATV 2017 running android 7.0 and I would like to mount my smb shares into the android file system. The main reason is, that the stock video app have no smb support and all other media player apps have some video stuttering and audio issues. 
I could install the google samba client on my tv and I was able to create a share successfully. Then I tried the suggested app (Shortcut maker for DocumentsUI) from an other issue. But the shortcut could not be found. 
Is there any hope in the future to use the samba client on android TVs?

**Comment by ttanxu** [comment]
Hmm... I don't think Android TV (nor does Android wear) has Downloads/Files app.

This app is the central coordinator of Storage Access Framework, the Android technology Android Samba Client uses to expose files to other apps. Therefore I don't think you can use this app on a TV.

Sorry.
