### ISSUE TITLE
Path? 

### ISSUE THREAD

**Issue by fretnutt** [google/samba-documents-provider#4]
Any instructions?

**Comment by ttanxu** [comment]
It's either `smb://<smb_server>/<file_share_path>` or `\\<smb_server>\<file_share_path>`. `<smb_server>` can be IP address, NBNS broadcast or a valid domain name. `<file_share_path>` is the share name under the SMB server (the folder name right under the SMB server if you can browse to the file share using Windows, Mac OS X or common Linux distros)

You should be able to derive it from your SMB server settings as well.

**Comment by fretnutt** [comment]
Thanks
