### ISSUE TITLE
mount successful, but cannot access remote files on Nexus 5

### ISSUE THREAD

**Issue by ksaerdna** [google/samba-documents-provider#44]
The mount operation (smb://fritz.box/FRITZ.NAS) was told to have been successful, and the input line has been cleared. However, there is nothing to be seen, neither in app "Download" nor in app "Einstellungen/Speicher & USB/".

I have the standard of the standard devices (Nexus 5 with original 6.0.1 ROM) and standard applications.

The ASUS file manager app has no problems to access the NAS.

**Comment by ttanxu** [comment]
Well... if you open Gmail and try to attach an attachment, the file share should be there.

This is WAI for Android Marshmallow. Downloads app can see file shares, but only exposed them in file chooser, not file manager :(.
