### ISSUE TITLE
"Share is already mounted" but no way to access it.

### ISSUE THREAD

**Issue by ognjenio** [google/samba-documents-provider#47]
1. Mount a share.
2. Close the share window. 
3. Try to mount the share again and get the message in title but no other way to access the share. Doesn't appear in Files or Downloads.

**Comment by ognjenio** [comment]
Android 7. Samsung Galaxy S8+

**Comment by ttanxu** [comment]
Ah... You need to contact Samsung for this, since you're using Android Nougat already. We have Downloads app shipped w/ AOSP image, but Samsung hides it from launcher.

This is a dup to #37.
