### ISSUE TITLE
In program - Failed to mount share. Please try again.

### ISSUE THREAD

**Issue by Yoda49** [google/samba-documents-provider#48]
In program - Failed to mount share. Please try again.
I write path "smb://storage/my_card", but get error message.

**Comment by ttanxu** [comment]
Hmm... This is a very general error -- basically anything that's not malformed share path or authentication belongs to this category. Can you share your logcat?

**Comment by Yoda49** [comment]
This is my mistake. I confused the saba client with the samba server...

**Comment by ttanxu** [comment]
Good you've solved the problem :)
