### ISSUE TITLE
No way to connect a shared folder LG k8

### ISSUE THREAD

**Issue by hiddenotebook** [google/samba-documents-provider#49]
I only have one chance to see the files and even to play videos from a shared folder. Then I close this app and now I can't figure it  how to open the shared folder. If I try to mount again it drops an error.

Sorry for my English

**Comment by ttanxu** [comment]
It's normal if you're using Marshmallow. You can only use it when picking a file -- such as attaching an attachment. If you're using Nougat, LG hides Downloads app in Android system and there is not much we can do about it.

Dup to #37.
