### ISSUE TITLE
Error:error: '../../../../src/main/jniLibs/x86_64/libsmbclient.so', needed by '../../../../build/intermediates/cmake/debug/obj/x86_64/libsamba_client.so', missing and no known rule to make it

### ISSUE THREAD

**Issue by mustafal** [google/samba-documents-provider#59]
Hello,
I had clone your repo and I have this error while running the app on the device.
`Error:error: '../../../../src/main/jniLibs/x86_64/libsmbclient.so', needed by '../../../../build/intermediates/cmake/debug/obj/x86_64/libsamba_client.so', missing and no known rule to make it`
Please help me out.

**Comment by huanyuan** [comment]
I clone it and has same problem like you ,now you how to solve it? please help me...

**Comment by mustafal** [comment]
I still didn't get any solution @huanyuan

**Comment by jerrychong25** [comment]
Just curious, have you followed build instructions in https://github.com/google/samba-documents-provider/blob/master/README.md?

```
Build Steps
1. Download and unarchive Samba 4.5.1 source code.
2. Change directory to the root of Samba source code.
3. Create a git repository.
4. Run git apply <path_to_samba_documents_provider_source>/sambapatch.diff.
5. Modify configure.sh to change $NDK to point to your NDK folder.
6. Uncomment corresponding flags in configure.sh to compile for different architecture. Uncomment flags for ARMv7 in addition to 32-bit ARM to compile it for ARMv7.
7. Run configure.sh to configure Samba project.
8. Run compile.sh to compile libsmbclient.so.
9. Run install.sh <path_to_samba_documents_provider_source>/app/src/main/jniLibs/<ABI>.
10. Change directory to SambaDocumentsProvider source code.
11. Run mv app/src/main/jniLibs/<ABI>/includes app/src/main/cpp/samba_includes.
12. Change directory to the root of Samba source code and run make distclean.
13. Repeat step 6-12 for all desired ABI's.
14. Make sure to change app's build.gradle to include only ABI's that Samba was built for in previous steps.
15. Compile SambaDocumentsProvider.
```

**Comment by mustafal** [comment]
I had found another solution of the [SmbClient](https://www.jcifs.org/) and used it successfully so I am closing this issue.

**Comment by jerrychong25** [comment]
> I had found another solution of the [SmbClient](https://www.jcifs.org/) and used it successfully so I am closing this issue.

You also can implement via one of the following:
1) jcifs-ng - https://github.com/AgNO3/jcifs-ng
2) smbj - https://github.com/hierynomus/smbj

**Comment by sathishmscict** [comment]
> I had found another solution of the [SmbClient](https://www.jcifs.org/) and used it successfully so I am closing this issue.

Could you please share , how you implemented. Am also facing same issue, please share some description it may be useful for me and other.
