### ISSUE TITLE
macOS - wscript:223: error: could not configure a c compiler!

### ISSUE THREAD

**Issue by jerrychong25** [google/samba-documents-provider#61]
Hi all,

I am trying to build this Android project in my **macOS** laptop.

However, when doing **Step 7 (Run configure.sh to configure Samba project)**, it have following errors:
```
macusers-MacBook:samba-4.5.1 HighSierra$ ./configure.sh
Creating standalone toolchain...
./configure.sh: line 50: /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
Configuring Samba...
Checking for program gcc or cc           : ['/Users/HighSierra/Desktop/samba-4.5.1/cc_shim.py', '/Users/HighSierra/Desktop/samba-4.5.1/bin/ndk/toolchain/bin/clang'] 
/Users/HighSierra/Desktop/samba-4.5.1/lib/replace/../../buildtools/wafsamba/wscript:223: error: could not configure a c compiler!
```

Could anyone assist on solving this issue?

Similar issue: https://github.com/google/samba-documents-provider/issues/55

Thanks.

**Comment by jerrychong25** [comment]
Can't found a solution for this issue.

In the end, I have implemented [smbj](https://github.com/hierynomus/smbj) library for accessing Samba Files instead.

**Comment by xiaoyg** [comment]
/ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory

NDK的路径不对

**Comment by jerrychong25** [comment]
> /ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory
> 
> NDK的路径不对

谢谢，但是我已经使用另一个Library成功实现Samba Access了。
