### ISSUE TITLE
Enable SMB3

### ISSUE THREAD

**Issue by ttanxu** [google/samba-documents-provider#7]
Need to modify the configuration file to allow SMB2 & SMB3.

For some reason libsmbclient out of the box uses maximum SMB1 protocol. They're preparing Samba 4.7.0 to make it default to SMBv3.

**Comment by voltagex** [comment]
Also, SMB1 should most definitely be disabled.

**Comment by voltagex** [comment]
I've bumped it to SMB2 in #10, but I didn't see anything that restricts the use of SMB3.

**Comment by ttanxu** [comment]
Yeah according to our contact in samba.org only from samba 2.7.0 (which is still in RC) did they start to use SMB3 by default.

There are devices (ASUS routers for example) that doesn't support SPNEGO, so I'm pretty sure there are still users for SMB1.

The configuration Samba provides is pretty coarse (no default protocol) so I think it's worth to expose this file so that folks can edit it based on their needs.

**Comment by ttanxu** [comment]
With respect of that change, the default maximum protocol is SMBv1 out of the box, so we need to add configuration to enable SMBv3.

**Comment by jrasamba** [comment]
FYI: "from samba 2.7.0 (which is still in RC)" - I think you mean Samba 4.7.0rc1 :-).

Samba provides many default protocol settings:

client ipc maxprotocol/client ipc minprotocol
client max protocol/client min  protocol
client use spnego

(and all the similar server settings of course).

**Comment by ttanxu** [comment]
Jeremy is correct. I meant 4.7.0rc1.

By "default protocol" I mean we can set min/max, but there is no priority order which allowed protocol is preferred, though it doesn't make sense to use lower version of protocol if both ends support it.

**Comment by jrasamba** [comment]
That's not how SMB protocol negotiation works. Now SMB3 is in place with man in the middle downgrade protection you always ask for SMB3, and client can then decide if a lower server protocol is acceptable. There's no way to downgrade seamlessly to SMB1.

Older protocol negotiation allowed the client to start with an SMB1 packet and then upgrading to SMB2, but you don't need to do that once you've got the client set to use SMB3.

**Comment by ttanxu** [comment]
Every time I thought about it I forgot mitm scenario. Pardon me because I don't work on network protocols so I don't always have that mind set. Though still if both ends agree on a set of protocols, it would still be nice to use the most advanced one because it usually has more benefits.

Anyway we'll change the default configuration, and expose it to external storage where user can change it if they need to loosen restrictions on SMBv1 & SPNEGO.
