### ISSUE TITLE
Mount location

### ISSUE THREAD

**Issue by wazz-up-dog** [google/samba-documents-provider#9]
On my LG G5 (rs988) I am unable to find the folder using the stock file manager.

**Comment by ttanxu** [comment]
Are you using Android Nougat? If you're running it on Android Lollipop or Marshmallow, you can only see it in file picker (e.g. pick an attachment in Gmail).

Otherwise you should be able to see it in Downloads app. Note LG may have its own file manager, which probably won't work with this app.

**Comment by wazz-up-dog** [comment]
Thank you for the quick response, I am running marshmallow, I do believe LG has their own file manager pre-installed, I checked Gmail and the folder was there, thank you again.
